[2024-05-16T11:22:31.743+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-16T11:22:31.771+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_tables.import_table3 manual__2024-05-16T11:22:29.083466+00:00 [queued]>
[2024-05-16T11:22:31.778+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_tables.import_table3 manual__2024-05-16T11:22:29.083466+00:00 [queued]>
[2024-05-16T11:22:31.779+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-05-16T11:22:31.806+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): import_table3> on 2024-05-16 11:22:29.083466+00:00
[2024-05-16T11:22:31.813+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=529) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-16T11:22:31.812+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_tables', 'import_table3', 'manual__2024-05-16T11:22:29.083466+00:00', '--job-id', '452', '--raw', '--subdir', 'DAGS_FOLDER/dag_mysql.py', '--cfg-path', '/tmp/tmp46o4z4as']
[2024-05-16T11:22:31.814+0000] {standard_task_runner.py:63} INFO - Started process 545 to run task
[2024-05-16T11:22:31.814+0000] {standard_task_runner.py:91} INFO - Job 452: Subtask import_table3
[2024-05-16T11:22:31.868+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_tables.import_table3 manual__2024-05-16T11:22:29.083466+00:00 [running]> on host 7084a6d88d3b
[2024-05-16T11:22:31.929+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bses' AIRFLOW_CTX_DAG_ID='dag_tables' AIRFLOW_CTX_TASK_ID='import_table3' AIRFLOW_CTX_EXECUTION_DATE='2024-05-16T11:22:29.083466+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-16T11:22:29.083466+00:00'
[2024-05-16T11:22:31.931+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-16T11:22:31.939+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-16T11:22:31.941+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n                mysql -h host.docker.internal -u root --password=12345678 test < /opt/***/dags/product_category_map.sql\n                ']
[2024-05-16T11:22:31.948+0000] {subprocess.py:86} INFO - Output:
[2024-05-16T11:22:32.106+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-16T11:22:32.110+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-16T11:22:32.140+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=dag_tables, task_id=import_table3, execution_date=20240516T112229, start_date=20240516T112231, end_date=20240516T112232
[2024-05-16T11:22:32.203+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-16T11:22:32.225+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-16T11:22:32.233+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
