[2024-05-16T11:19:48.832+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-16T11:19:48.854+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_tables.import_table2 scheduled__2024-05-04T00:00:00+00:00 [queued]>
[2024-05-16T11:19:48.862+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_tables.import_table2 scheduled__2024-05-04T00:00:00+00:00 [queued]>
[2024-05-16T11:19:48.862+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-05-16T11:19:48.885+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): import_table2> on 2024-05-04 00:00:00+00:00
[2024-05-16T11:19:48.895+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=229) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-16T11:19:48.893+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_tables', 'import_table2', 'scheduled__2024-05-04T00:00:00+00:00', '--job-id', '394', '--raw', '--subdir', 'DAGS_FOLDER/dag_mysql.py', '--cfg-path', '/tmp/tmp802el70t']
[2024-05-16T11:19:48.898+0000] {standard_task_runner.py:91} INFO - Job 394: Subtask import_table2
[2024-05-16T11:19:48.897+0000] {standard_task_runner.py:63} INFO - Started process 241 to run task
[2024-05-16T11:19:48.960+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_tables.import_table2 scheduled__2024-05-04T00:00:00+00:00 [running]> on host 7084a6d88d3b
[2024-05-16T11:19:49.028+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bses' AIRFLOW_CTX_DAG_ID='dag_tables' AIRFLOW_CTX_TASK_ID='import_table2' AIRFLOW_CTX_EXECUTION_DATE='2024-05-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-04T00:00:00+00:00'
[2024-05-16T11:19:49.031+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-16T11:19:49.054+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-16T11:19:49.055+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n                mysql -h host.docker.internal -u root --password=12345678 test < /opt/***/dags/product_category.sql;\n                ']
[2024-05-16T11:19:49.072+0000] {subprocess.py:86} INFO - Output:
[2024-05-16T11:19:49.194+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-16T11:19:49.195+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-16T11:19:49.220+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=dag_tables, task_id=import_table2, execution_date=20240504T000000, start_date=20240516T111948, end_date=20240516T111949
[2024-05-16T11:19:49.293+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-16T11:19:49.348+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-16T11:19:49.359+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-16T11:22:31.080+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-16T11:22:31.117+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_tables.import_table2 scheduled__2024-05-04T00:00:00+00:00 [queued]>
[2024-05-16T11:22:31.132+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_tables.import_table2 scheduled__2024-05-04T00:00:00+00:00 [queued]>
[2024-05-16T11:22:31.137+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-05-16T11:22:31.166+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): import_table2> on 2024-05-04 00:00:00+00:00
[2024-05-16T11:22:31.179+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=485) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-16T11:22:31.189+0000] {standard_task_runner.py:63} INFO - Started process 500 to run task
[2024-05-16T11:22:31.182+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_tables', 'import_table2', 'scheduled__2024-05-04T00:00:00+00:00', '--job-id', '442', '--raw', '--subdir', 'DAGS_FOLDER/dag_mysql.py', '--cfg-path', '/tmp/tmp8tzjjf0t']
[2024-05-16T11:22:31.195+0000] {standard_task_runner.py:91} INFO - Job 442: Subtask import_table2
[2024-05-16T11:22:31.266+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_tables.import_table2 scheduled__2024-05-04T00:00:00+00:00 [running]> on host 7084a6d88d3b
[2024-05-16T11:22:31.378+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bses' AIRFLOW_CTX_DAG_ID='dag_tables' AIRFLOW_CTX_TASK_ID='import_table2' AIRFLOW_CTX_EXECUTION_DATE='2024-05-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-04T00:00:00+00:00'
[2024-05-16T11:22:31.380+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-16T11:22:31.387+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-16T11:22:31.388+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n                mysql -h host.docker.internal -u root --password=12345678 test < /opt/***/dags/product_category.sql\n                ']
[2024-05-16T11:22:31.395+0000] {subprocess.py:86} INFO - Output:
[2024-05-16T11:22:31.535+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-16T11:22:31.536+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-16T11:22:31.581+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=dag_tables, task_id=import_table2, execution_date=20240504T000000, start_date=20240516T112231, end_date=20240516T112231
[2024-05-16T11:22:31.668+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-16T11:22:31.772+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-16T11:22:31.779+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-16T11:24:46.127+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-16T11:24:46.191+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_tables.import_table2 scheduled__2024-05-04T00:00:00+00:00 [queued]>
[2024-05-16T11:24:46.199+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_tables.import_table2 scheduled__2024-05-04T00:00:00+00:00 [queued]>
[2024-05-16T11:24:46.200+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-05-16T11:24:46.234+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): import_table2> on 2024-05-04 00:00:00+00:00
[2024-05-16T11:24:46.267+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_tables', 'import_table2', 'scheduled__2024-05-04T00:00:00+00:00', '--job-id', '485', '--raw', '--subdir', 'DAGS_FOLDER/dag_mysql.py', '--cfg-path', '/tmp/tmpu_hy_pmn']
[2024-05-16T11:24:46.273+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=697) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-16T11:24:46.281+0000] {standard_task_runner.py:63} INFO - Started process 721 to run task
[2024-05-16T11:24:46.281+0000] {standard_task_runner.py:91} INFO - Job 485: Subtask import_table2
[2024-05-16T11:24:46.376+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_tables.import_table2 scheduled__2024-05-04T00:00:00+00:00 [running]> on host 7084a6d88d3b
[2024-05-16T11:24:46.515+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bses' AIRFLOW_CTX_DAG_ID='dag_tables' AIRFLOW_CTX_TASK_ID='import_table2' AIRFLOW_CTX_EXECUTION_DATE='2024-05-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-04T00:00:00+00:00'
[2024-05-16T11:24:46.520+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-16T11:24:46.535+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-16T11:24:46.536+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n                mysql -h host.docker.internal -u root --password=12345678 test < /opt/***/dags/product_category.sql\n                ']
[2024-05-16T11:24:46.552+0000] {subprocess.py:86} INFO - Output:
[2024-05-16T11:24:46.711+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-16T11:24:46.719+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-16T11:24:46.749+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=dag_tables, task_id=import_table2, execution_date=20240504T000000, start_date=20240516T112446, end_date=20240516T112446
[2024-05-16T11:24:46.808+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-16T11:24:46.830+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-16T11:24:46.834+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
