[2024-05-19T03:19:50.315+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-19T03:19:50.330+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_analysis.analysis scheduled__2024-05-16T00:00:00+00:00 [queued]>
[2024-05-19T03:19:50.334+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_analysis.analysis scheduled__2024-05-16T00:00:00+00:00 [queued]>
[2024-05-19T03:19:50.334+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-05-19T03:19:50.341+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): analysis> on 2024-05-16 00:00:00+00:00
[2024-05-19T03:19:50.345+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=311) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-19T03:19:50.346+0000] {standard_task_runner.py:63} INFO - Started process 317 to run task
[2024-05-19T03:19:50.346+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_analysis', 'analysis', 'scheduled__2024-05-16T00:00:00+00:00', '--job-id', '590', '--raw', '--subdir', 'DAGS_FOLDER/dag1.py', '--cfg-path', '/tmp/tmpqptgw3gi']
[2024-05-19T03:19:50.347+0000] {standard_task_runner.py:91} INFO - Job 590: Subtask analysis
[2024-05-19T03:19:50.371+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_analysis.analysis scheduled__2024-05-16T00:00:00+00:00 [running]> on host cf8d95dc7aa1
[2024-05-19T03:19:50.412+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bses' AIRFLOW_CTX_DAG_ID='dag_analysis' AIRFLOW_CTX_TASK_ID='analysis' AIRFLOW_CTX_EXECUTION_DATE='2024-05-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-16T00:00:00+00:00'
[2024-05-19T03:19:50.413+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-19T03:19:50.469+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/dag1.py:15 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-05-19T03:19:50.514+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/dag1.py:17 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-05-19T03:19:50.516+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/dag1.py:19 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-05-19T03:19:50.519+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/dag1.py:21 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-05-19T03:19:50.521+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/dag1.py:23 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-05-19T03:19:50.576+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-19T03:19:50.576+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-19T03:19:50.581+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=dag_analysis, task_id=analysis, execution_date=20240516T000000, start_date=20240519T031950, end_date=20240519T031950
[2024-05-19T03:19:50.607+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-19T03:19:50.616+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-19T03:19:50.617+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-19T03:21:03.118+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-19T03:21:03.131+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_analysis.analysis scheduled__2024-05-16T00:00:00+00:00 [queued]>
[2024-05-19T03:21:03.135+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_analysis.analysis scheduled__2024-05-16T00:00:00+00:00 [queued]>
[2024-05-19T03:21:03.135+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-05-19T03:21:03.141+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): analysis> on 2024-05-16 00:00:00+00:00
[2024-05-19T03:21:03.145+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=413) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-19T03:21:03.147+0000] {standard_task_runner.py:63} INFO - Started process 419 to run task
[2024-05-19T03:21:03.146+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_analysis', 'analysis', 'scheduled__2024-05-16T00:00:00+00:00', '--job-id', '609', '--raw', '--subdir', 'DAGS_FOLDER/dag1.py', '--cfg-path', '/tmp/tmpa73wnqnm']
[2024-05-19T03:21:03.147+0000] {standard_task_runner.py:91} INFO - Job 609: Subtask analysis
[2024-05-19T03:21:03.170+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_analysis.analysis scheduled__2024-05-16T00:00:00+00:00 [running]> on host cf8d95dc7aa1
[2024-05-19T03:21:03.209+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bses' AIRFLOW_CTX_DAG_ID='dag_analysis' AIRFLOW_CTX_TASK_ID='analysis' AIRFLOW_CTX_EXECUTION_DATE='2024-05-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-16T00:00:00+00:00'
[2024-05-19T03:21:03.209+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-19T03:21:03.264+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/dag1.py:15 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-05-19T03:21:03.323+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/dag1.py:17 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-05-19T03:21:03.326+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/dag1.py:19 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-05-19T03:21:03.328+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/dag1.py:21 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-05-19T03:21:03.330+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/dag1.py:23 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-05-19T03:21:03.384+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-19T03:21:03.384+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-19T03:21:03.389+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=dag_analysis, task_id=analysis, execution_date=20240516T000000, start_date=20240519T032103, end_date=20240519T032103
[2024-05-19T03:21:03.409+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-19T03:21:03.418+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-19T03:21:03.419+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
