[2024-05-15T10:15:44.503+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-15T10:15:44.525+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_hdfs.fetch scheduled__2024-05-08T00:00:00+00:00 [queued]>
[2024-05-15T10:15:44.531+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_hdfs.fetch scheduled__2024-05-08T00:00:00+00:00 [queued]>
[2024-05-15T10:15:44.532+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-05-15T10:15:44.539+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): fetch> on 2024-05-08 00:00:00+00:00
[2024-05-15T10:15:44.544+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=280) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-15T10:15:44.543+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_hdfs', 'fetch', 'scheduled__2024-05-08T00:00:00+00:00', '--job-id', '161', '--raw', '--subdir', 'DAGS_FOLDER/hdfs_dag.py', '--cfg-path', '/tmp/tmpuqde_4nu']
[2024-05-15T10:15:44.548+0000] {standard_task_runner.py:63} INFO - Started process 300 to run task
[2024-05-15T10:15:44.549+0000] {standard_task_runner.py:91} INFO - Job 161: Subtask fetch
[2024-05-15T10:15:44.577+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_hdfs.fetch scheduled__2024-05-08T00:00:00+00:00 [running]> on host f85b7a0b58b5
[2024-05-15T10:15:44.614+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bses' AIRFLOW_CTX_DAG_ID='dag_hdfs' AIRFLOW_CTX_TASK_ID='fetch' AIRFLOW_CTX_EXECUTION_DATE='2024-05-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-08T00:00:00+00:00'
[2024-05-15T10:15:44.615+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-15T10:15:44.621+0000] {logging_mixin.py:188} INFO - Error reading file from HDFS: /bin/sh: 1: hadoop: Permission denied
[2024-05-15T10:15:44.622+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-15T10:15:44.623+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-15T10:15:44.630+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=dag_hdfs, task_id=fetch, execution_date=20240508T000000, start_date=20240515T101544, end_date=20240515T101544
[2024-05-15T10:15:44.648+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-15T10:15:44.662+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-15T10:15:44.663+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
